name: Publishing on NPM

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - ./packages/react-external-renderer/package.json

permissions:
    contents: read
    id-token: write

jobs:
    publish-npm:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest
                  registry-url: "https://registry.npmjs.org"
                  cache: "pnpm"

            - name: Build package
              run: |
                  mv ./README.md ./packages/react-external-renderer/
                  pnpm install
                  pnpm run build

            - name: Publishing on NPM
              uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{secrets.NPM_TOKEN}}
                  access: public
                  provenance: true
